### ISSUE TITLE
Error "duplicate package ID is detected"

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#467]
Hey @freddydk , 

Our deployment just stopped working. I believe this is the first deployment after the latest AL-Go version update. Could it be something related?

Error received:
`A duplicate package ID is detected. Cannot publish an extension with packageId`

Any suggestion how to solve it? Do you need extra information?

**Comment by freddydk** [comment]
Is this in CD?
Are you deploying to more than one environment?

**Comment by gntpet** [comment]
Yes, I get this error during cicd. Deploying to single environment.

**Comment by freddydk** [comment]
Any chance you can add me to the repo?

**Comment by freddydk** [comment]
Very strange - as every build of an app should create a new package id.
Can I see a full output of the workflow maybe?

**Comment by gntpet** [comment]
Sent logs through yammer

**Comment by freddydk** [comment]
I think this was fixed by the latest ContainerHelper change right?

**Comment by gntpet** [comment]
if latest containerhelper is 4.0.16, then it was not fixed. Got this issue again on 24th of April

**Comment by freddydk** [comment]
Ahh - probably still in preview - will be published one of the next days.

**Comment by gntpet** [comment]
Still facing this issue. Did you publish new version?

**Comment by buzzwick** [comment]
Running into this same problem, see #3203. AL-Go system files are up to date.
