### ISSUE TITLE
Issue with updating Al-Go System files

### ISSUE THREAD

**Issue by gntpet** [microsoft/AL-Go#757]
Hey there, 

We are testing github larger runners, to see if we can get performance boost for our pipelines, and after the change we noticed that we cannot update al-go system files.

We do receive the following error. It seems that githubcli is missing on larger runners? (our token is valid 100%)

`Error: Unexpected error when running action. Error Message: Failed to create a pull-request to AL-Go System Files. Make sure that the personal access token, defined in the secret called GhTokenWorkflow, is not expired and it has permission to update workflows. (Error was It looks like GitHub CLI is not installed. Please install GitHub CLI from https://cli.github.com/), StackTrace: at <ScriptBlock>, D:\a\_actions\microsoft\AL-Go-Actions\v3.2\CheckForUpdates\CheckForUpdates.ps1: line 530 <- at <ScriptBlock>, D:\a\_temp\77c97522-6a77-4de7-a38c-686f899cdc2f.ps1: line 4 <- at <ScriptBlock>, <No file>: line 1`

Nevertheless, according to documentation it should not even run on another runner, and must use windows-latest

![image](https://github.com/microsoft/AL-Go/assets/16342128/3c8cc63d-ab64-459e-a88e-e8cd9ada05af)

But in reality it's using my new runner
![image](https://github.com/microsoft/AL-Go/assets/16342128/5aaa484a-b8cb-44b0-a922-3b941037a0ea)

Here's our config file
![image](https://github.com/microsoft/AL-Go/assets/16342128/4d6f78aa-e479-49cc-8ce8-bb8e8b78e394)

In addition, could you please explain what's the difference between two AL-GO settings  "runs-on" & "githubrunner". It's sounds that they are exactly the same.

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
Some confusion in the docs there, I will change that.
"runs-on" is used for all jobs, which doesn't build/test your app. This is jobs that doesn't require a lot of machine power.
"githubRunner" is used for build/test jobs. This is jobs, which requires more memory.

**Comment by freddydk** [comment]
The "missing" GitHub CLI was caused by a bug in BcContainerHelper (not really a missing GH CLI)
This is fixed in containerhelper v6.0.0, which has shipped now and should be picked up by your workflow.

I will investigate why Update AL-Go system files picks your "self-hosted runner" - it shouldn't

**Comment by gntpet** [comment]
hey @freddydk, 
I just tried it again, but still receive the same error. 

![image](https://github.com/microsoft/AL-Go/assets/16342128/e403cc63-2a59-4aa1-a11e-c6e762a0d26d)

it is still using the same old BCcontainerhelper version

![image](https://github.com/microsoft/AL-Go/assets/16342128/25df8302-5b67-4ec5-bcad-e33b958eac7b)

**Comment by freddydk** [comment]
Unfortunately the CDN takes days to see that a new version is available - I have requested a purge of the CDN - but not sure when it happens.
It should just work (very soon) - sorry:-(

**Comment by gntpet** [comment]
No worries. Now, it picked up the latest version and system file updated run successfully. Thank you

**Comment by freddydk** [comment]
Doc update: https://github.com/microsoft/AL-Go/pull/762

**Comment by freddydk** [comment]
Shipped in v4.0
