### ISSUE TITLE
Resource not accessible by integration when creating release from specific version

### ISSUE THREAD

**Issue by mstoilov-isystems-group** [microsoft/AL-Go#987]
Hello,

I am facing an issue when I try to create a release from specific app version ( when using "lates" everything works correctly ).

Below you can see the permissions of the token that I am using, workflow parameters and the error. It happens no matter if useGhTokenWorkflow is true or false and only when you specify app version. 

![image](https://github.com/microsoft/AL-Go/assets/144775121/d1ea3cd6-36f2-4bfa-97f8-bf2d0d7a3ea7)

![image](https://github.com/microsoft/AL-Go/assets/144775121/3f3f2916-378d-49b0-b062-4b6fdbf5a4e2)

`Error: Unhandled error: HttpError: Resource not accessible by integration
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:4:31)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:20) {
  status: [40](https://github.com/isystems-group/D365BC_BGFISCAL/actions/runs/8308683091/job/22739180142#step:10:41)3,
  response: {
    url: 'https://api.github.com/repos/isystems-group/D365BC_BGFISCAL/releases',
    status: 403,
    headers: {
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
      connection: 'close',
      'content-encoding': 'gzip',
      'content-security-policy': "default-src 'none'",
      'content-type': 'application/json; charset=utf-8',
      date: 'Sat, 16 Mar 2024 15:16:19 GMT',
      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
      server: 'GitHub.com',
      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
      'transfer-encoding': 'chunked',
      vary: 'Accept-Encoding, Accept, X-Requested-With',
      'x-accepted-github-permissions': 'contents=write; contents=write,workflows=write',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'deny',
      'x-github-api-version-selected': '2022-11-28',
      'x-github-media-type': 'github.v3; format=json',
      'x-github-request-id': 'D000:326351:14775:23BC6:65F5B7C3',
      'x-ratelimit-limit': '5000',
      'x-ratelimit-remaining': '4970',
      'x-ratelimit-reset': '1710604606',
      'x-ratelimit-resource': 'core',
      'x-ratelimit-used': '30',
      'x-xss-protection': '0'
    },
    data: {
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/releases/releases#create-a-release'
    }
  },
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/isystems-group/D365BC_BGFISCAL/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'actions/github-script octokit-core.js/3.6.0 Node.js/16.20.2 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: `{"tag_name":"20.7.0","name":"v20.7test","body""}`,
    request: { agent: [Agent], hook: [Function: bound bound register] }
  }`

**Comment by mstoilov-isystems-group** [comment]
Disabling and enabling the actions in the repo does not fixes the issue.

**Comment by freddydk** [comment]
I think this is the same as #973 and should be fixed in preview.
Could you update AL-Go System Files with the preview version (microsoft/AL-Go-PTE@preview or microsoft/AL-Go-AppSource@preview) and then retry the operation?

**Comment by mstoilov-isystems-group** [comment]
I have tried with the preview version, but the issue persisted. In my case the right artifact is found, but the error occurs on the final step when the pipeline uses github-script@v7 to create the release. It looks like there is a problem with the token that is used.
It's odd because if you target "latest" as appVersion and not specific build, everything works fine.

![image](https://github.com/microsoft/AL-Go/assets/144775121/efb67e88-5f67-4928-b841-4675ad6e7aaf)

**Comment by freddydk** [comment]
Just remember having seen this when trying to create a release in a fork - is this the case?

**Comment by freddydk** [comment]
If you try to create a release in GitHub (without the workflow) - does that work?

**Comment by mstoilov-isystems-group** [comment]
I am not trying to create it from a fork. It is from the primary repo and from the main branch, just not using latest, but a version from previous build - 20.7.14.0. ( There is one more build 20.7.15.0 , which is the latest, but I don't want to create the release from that build )

When creating the release manually it works.

**Comment by freddydk** [comment]
Could you post the full log from the workflow run here? (all jobs)

**Comment by mstoilov-isystems-group** [comment]
These are the exported log files from the job.
[logs_21801483316.zip](https://github.com/microsoft/AL-Go/files/14633672/logs_21801483316.zip)

**Comment by freddydk** [comment]
And could you also share a log of the successful create release with latest build?
+ list the releases in the repo
+ list the tag names
+ what are the settings under settings -> actions -> general -> workflow permissions?

**Comment by mstoilov-isystems-group** [comment]
Just created a release with same props, but with target latest ( tags and releases below are before this release ). This is the log:
[logs_21825504462.zip](https://github.com/microsoft/AL-Go/files/14634057/logs_21825504462.zip)

Tags:
![image](https://github.com/microsoft/AL-Go/assets/144775121/24c41792-1162-4f81-aa1c-c95342da5c91)

Releases:
v20.6 - tag 20.6.0
v20.5 - tag 20.5.0
v20.4 - tag 20.4.0

settings -> actions -> general -> workflow permissions:
![image](https://github.com/microsoft/AL-Go/assets/144775121/c61dba05-c530-49d9-89a0-e10dd0906e07)

**Comment by freddydk** [comment]
I have a repro now here - will troubleshoot
![image](https://github.com/microsoft/AL-Go/assets/10775043/78792293-d884-4b29-9791-e47886bbbbf8)

**Comment by freddydk** [comment]
Earlier, we used a github action to create the release. That one was deprecated and we shifted to use the API instead. Looks like the new implementation doesn't support this scenario at this time.
If you create a tag manually with the commit SHA for which you need to create the release, then you will be able to create the release with that commitish. This behavior should obviously be part of the workflow.
